import "../styles/globals.css";
import ThemeWrapper from "@/modules/Next-themes/ThemeWrapper";
import NavBar from "@/components/NavBar/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="font-['Inter']">
        <ThemeWrapper>
          <NavBar />
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}
